{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    alb.ingress.kubernetes.io/subnets: subnet-0ec5acd99a404b006,subnet-0b56cd4627314d060,subnet-032b41722dc0a8e59
    alb.ingress.kubernetes.io/scheme: internet-facing
    nginx.ingress.kubernetes.io/use-regex: "true"
    alb.ingress.kubernetes.io/group.name: smachno-group # Назва групи
    alb.ingress.kubernetes.io/group.order: '1'          # Пріоритет (бек має бути другим)
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 80
{{- end }}