name: Terraform Apply Infrastructure (AWS)

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Тільки якщо зміни у папці terraform
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**' # Тільки якщо зміни у папці terraform

# Дозволи для OIDC та коментарів у PR
permissions:
  contents: read
  id-token: write # Для автентифікації OIDC в AWS
  pull-requests: write # Для коментарів з планом

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          #Вказуйте ARN ролі, яку GitHub Actions має взяти на себе
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1 # Ваш регіон AWS

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Add Plan to Pull Request Comment
        # Цей крок виконується тільки для Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        env:
          PLAN: "```hcl\n${{ steps.plan.outputs.stdout }}\n```"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖

            ${process.env.PLAN}

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Apply
        # Запускати тільки при пуші в main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan # Застосовуємо збережений план, щоб гарантувати відповідність